#!/bin/bash

current_dir=$(pwd)

if [ -z $1  ]; then
    echo -e "\033[0;31m\nPlease provide the backup directory at the first argument\033[0m\n"
    exit 1
fi

cd $1

if [ ! -f .env ]; then
    echo -e "\033[0;31m\nPlease create .env file\033[0m\n"
    exit 1
fi

if [ ! command -v ssh &> /dev/null ]; then
    sudo apt update
    echo "Installing ssh..."
    sudo apt install ssh -y
fi

if [ ! command -v sshpass &> /dev/null ]; then
    sudo apt update
    echo "Installing sshpass..."
    sudo apt install sshpass -y
fi

if [ ! command -v rsync &> /dev/null ]; then
    sudo apt update
    echo "Installing rsync..."
    sudo apt install rsync -y
fi

source .env

rsync -avz -e "sshpass -p $password ssh -p $port" $username@$remote:$workspace .

if [ ! $? -eq 0 ]; then
    echo -e "\033[0;31m\nBackup failed\033[0m\n"
    exit 1
fi

echo -e "\033[0;32m\nDone backup\033[0m\n"
cd $current_dir
